name: CodeTester

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore KitchenAPI/KitchenAPI.csproj ClassLibrary/ClassLibrary.csproj Frontend/Frontend.csproj UnitTests/UnitTests.csproj

      - name: Build
        run: dotnet build KitchenAPI/KitchenAPI.csproj ClassLibrary/ClassLibrary.csproj Frontend/Frontend.csproj UnitTests/UnitTests.csproj --no-restore

      - name: Run tests
        run: dotnet test UnitTests/UnitTests.csproj --no-build --verbosity normal

      - name: Lint code
        run: dotnet format --check

      - name: CSV Validation
        run: pwsh .github/workflows/validate-csv.ps1
