CREATE TABLE [dbo].[InventorieTable]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [ProductID] UNIQUEIDENTIFIER NOT NULL, 
    [Amount] FLOAT NOT NULL, 
    [EP] DATETIME NOT NULL, 
    [Owner] UNIQUEIDENTIFIER NOT NULL
)
